name: Android CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'           # 添加 tag 触发器，当推送 v 开头的tag时触发
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SIGNING_STORE_PASSWORD: "123456"
      SIGNING_KEY_ALIAS: "release"
      SIGNING_KEY_PASSWORD: "123456"

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    # 创建 GitHub Release
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')  # 只在有tag时创建release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
        name: Release ${{ github.ref_name }}
        body: |
          Release ${{ github.ref_name }}
          
          自动构建发布
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 